
define run_java_file
	javac $(1).java && java $(1)
endef

SwapNodesInPairs:
	$(call run_java_file,SwapNodesInPairs)

LongestSubstringWithoutRepeatingCharacters:
	$(call run_java_file,LongestSubstringWithoutRepeatingCharacters)

addTwoNumbers:
	$(call run_java_file,AddTwoNumbers)

twoSum:
	$(call run_java_file,TwoSum)

clean:
	rm -rf *.class
