
define run_java_file
	javac $(1).java && java $(1)
endef

MedianOfTwoSortedArrays:
	$(call run_java_file,MedianOfTwoSortedArrays)

MergeKSortedLists:
	$(call run_java_file,MergeKSortedLists)

LinkedListCycle:
	$(call run_java_file,LinkedListCycle)

ReverseLinkedList:
	$(call run_java_file,ReverseLinkedList)

SwapNodesInPairs:
	$(call run_java_file,SwapNodesInPairs)

LongestSubstringWithoutRepeatingCharacters:
	$(call run_java_file,LongestSubstringWithoutRepeatingCharacters)

addTwoNumbers:
	$(call run_java_file,AddTwoNumbers)

twoSum:
	$(call run_java_file,TwoSum)

clean:
	rm -rf *.class
