
define run_java_file
	javac $(1).java && java $(1)
endef

PalindromeNumber:
	$(call run_java_file,PalindromeNumber)

StringToInteger:
	$(call run_java_file,StringToInteger)

ReverseInteger:
	$(call run_java_file,ReverseInteger)

ZigZagConversion:
	$(call run_java_file,ZigZagConversion)

LongestPalindromicSubstring:
	$(call run_java_file,LongestPalindromicSubstring)

MedianOfTwoSortedArrays:
	$(call run_java_file,MedianOfTwoSortedArrays)

QuickSort:
	$(call run_java_file,QuickSort)

BinarySearch:
	$(call run_java_file,BinarySearch)

MergeKSortedLists:
	$(call run_java_file,MergeKSortedLists)

LinkedListCycle:
	$(call run_java_file,LinkedListCycle)

ReverseLinkedList:
	$(call run_java_file,ReverseLinkedList)

SwapNodesInPairs:
	$(call run_java_file,SwapNodesInPairs)

LongestSubstringWithoutRepeatingCharacters:
	$(call run_java_file,LongestSubstringWithoutRepeatingCharacters)

addTwoNumbers:
	$(call run_java_file,AddTwoNumbers)

twoSum:
	$(call run_java_file,TwoSum)

clean:
	rm -rf *.class
